#!/usr/bin/bash
ps1=`ps --no-headers -o comm 1`
if [ "$ps1" == "systemd" ];then
    cp /opt/powerplan/powerplan.service /etc/systemd/system/
    systemctl daemon-reload
    systemctl enable powerplan
    systemctl start powerplan
    echo "Done."
else
    echo "powerplan\'s daemon needs Systemd."
fi
