#!/usr/bin/bash
ps1=`ps --no-headers -o comm 1`
if [ "$ps1" == "systemd" ];then
    cp /opt/cpuauto/cpuauto.service /etc/systemd/system/
    systemctl daemon-reload
    systemctl enable cpuauto
    systemctl start cpuauto
    echo "Done."
else
    echo "cpuauto\'s daemon needs Systemd."
fi
