#!/usr/bin/bash
# uninstall first if installation detected
[ -d "/opt/powerplan/" ] && ./uninstall

# Proceed with normal installation
mkdir /opt/powerplan/
mkdir /opt/powerplan/src/
cp -r src/*.py /opt/powerplan/src/
cp uninstall /opt/powerplan/
cp enable-daemon /opt/powerplan/
cp powerplan.service /opt/powerplan/
cp LICENSE /opt/powerplan/LICENSE
ln -s /opt/powerplan/src/powerplan.py /usr/bin/powerplan
chmod 755 /opt/powerplan/src/powerplan.py
chmod 755 /opt/powerplan/uninstall
chmod 755 /usr/bin/powerplan
chmod 744 /opt/powerplan/enable-daemon
chmod 644 /opt/powerplan/powerplan.service
