#!/usr/bin/bash

# Systemd daemon
if [[ -f "/etc/systemd/system/powerplan.service" ]];then
    systemctl stop powerplan
    systemctl disable powerplan
    systemctl daemon-reload
    rm /etc/systemd/system/powerplan.service
fi

# Everything else
rm /usr/bin/powerplan
rm -r /opt/powerplan
